#!/bin/sh

echo "starting..."

if [ -z "${MMS_API_KEY}" ]; then echo "Missing MMS_API_KEY variable"; sleep 2s; exit 1; fi
if [ -z "${MMS_GROUP_ID}" ]; then echo "Missing MMS_GROUP_ID variable"; sleep 2s; exit 1; fi

envsubst < /etc/mongodb-mms/templates/monitoring-agent.config > /etc/mongodb-mms/monitoring-agent.config

exec mongodb-mms-monitoring-agent --conf /etc/mongodb-mms/monitoring-agent.config