#!/bin/sh

echo "starting..."

if [ -z "${MMS_API_KEY}" ]; then echo "Missing MMS_API_KEY variable"; sleep 2s; exit 1; fi
if [ -z "${MMS_GROUP_ID}" ]; then echo "Missing MMS_GROUP_ID variable"; sleep 2s; exit 1; fi

envsubst < /opt/templates/backup-agent.config > /etc/mongodb-mms/backup-agent.config

export INSTANCE_ID=$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-id)
export OLD_HOSTNAME=$(hostname)
hostname ${SITENAME}-${INSTANCE_ID}-BACKUP-${OLD_HOSTNAME}

exec mongodb-mms-backup-agent -c /etc/mongodb-mms/backup-agent.config