#!/bin/sh

echo "starting..."

if [ -z "${MMS_API_KEY}" ]; then echo "Missing MMS_API_KEY variable"; exit 1; fi

envsubst < /etc/mongodb-mms/templates/backup-agent.config > /etc/mongodb-mms/backup-agent.config

exec mongodb-mms-backup-agent -c /etc/mongodb-mms/backup-agent.config